name: autoease
description: "A car workshop mobile app."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # Internationalization
  flutter_localizations:
    sdk: flutter
    
  # UI
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.3
  responsive_framework: ^1.5.1
  syncfusion_flutter_calendar: ^27.1.53
  timelines: ^0.1.0
  skeletonizer: ^1.4.2

  # Routing
  go_router: ^14.3.0

  # Local Storage
  shared_preferences: ^2.3.2

  # State Management
  provider: ^6.1.2
  
  # Firebase (Auth & Datastore)
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1

  # Analytics
  firebase_analytics: ^11.3.3
  
  # Utils
  intl: ^0.19.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true