name: autoease
description: "A car workshop mobile app."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Internationalization
  flutter_localizations:
    sdk: flutter
    
  # UI
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.3
  responsive_framework: ^1.5.1
  syncfusion_flutter_calendar: ^27.1.55
  timelines_plus: ^1.0.3
  skeletonizer: ^1.4.2
  flutter_typeahead: ^4.8.0
  
  # Routing
  go_router: ^14.3.0

  # Local Storage
  shared_preferences: ^2.3.2

  # State Management
  provider: ^6.1.2

  # Receipt
  
  # Firebase (Auth & Datastore)
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1

  # Analytics
  firebase_analytics: ^11.3.3
  
  # Utils
  intl: ^0.19.0
  collection: ^1.18.0
  pdf: ^3.11.1
  printing: ^5.13.3
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
   - assets/images/
   - assets/icons/
   - assets/animations/

fonts:
  - family: Inter
    fonts:
      - asset: assets/fonts/Inter-Thin.ttf
        weight: 100
        style: normal

      - asset: assets/fonts/Inter-ExtraLight.ttf
        weight: 200
        style: normal

      - asset: assets/fonts/Inter-Light.ttf
        weight: 300
        style: normal

      - asset: assets/fonts/Inter-Regular.ttf
        weight: 400
        style: normal

      - asset: assets/fonts/Inter-Medium.ttf
        weight: 500
        style: normal

      - asset: assets/fonts/Inter-SemiBold.ttf
        weight: 600
        style: normal

      - asset: assets/fonts/Inter-Bold.ttf
        weight: 700
        style: normal

      - asset: assets/fonts/Inter-ExtraBold.ttf
        weight: 800
        style: normal

      - asset: assets/fonts/Inter-Black.ttf
        weight: 900
        style: normal